stages:
  clean_data:
    cmd: python src\data\clean_data.py
    deps:
    - ${data_source.data_folders}\training
    - src\data\clean_data.py
    params:
    - data_source.data_folders
    - data_source.training_data_folder.folder
    - data_source.training_data_folder.train
    - data_source.prepared.folder
    - data_source.prepared.clean_train
    outs:
    - ${data_source.data_folders}\prepared

  generate_training_features:
    cmd: python -W ignore src\data\generate_training_features.py #-W ignore: ignore all warning when executing the script
    deps:
      - ${data_source.data_folders}\prepared
      - src\data\generate_training_features.py
      - src\models\feature_eng      
    params:
        - data_source.data_folders # track specific param (from params.yaml)
        - data_source.prepared    # track specific param (from params.yaml)
        - featurize   # track specific param (from params.yaml)
        - src\data\train_params.yaml: # track specific params from custom file
            - train_test_split
            - training_data
            - test_data
            - pipeline_type
    outs:
      - ${data_source.data_folders}\feature\