stages:
  clean_data:
    cmd:  
        python src\data\clean_data.py
    deps:
    - data\training
    - src\data\clean_data.py
    params:
    - data_source.data_folders
    - data_source.training_data_folder.folder
    - data_source.training_data_folder.train
    - data_source.prepared.folder
    - data_source.prepared.clean_train
    outs:
    - data\prepared
