data_source:
  data_folders: data
  training_data_folder:
    folder: training
    train: train.csv
    test: test.csv
  prepared:
    folder: prepared
    clean_train: clean_train.csv

featurize:

  combine_feat:
    targetcol: ACTION
    ignore_columns:                                      #['ROLE_TITLE'] 
    - ROLE_TITLE
    - MGR_ID
    - RESOURCE
  resource_catagory_encode:
    column_to_consider:
    - ROLE_DEPTNAME_ROLE_FAMILY
    - ROLE_ROLLUP_1_ROLE_FAMILY
  ktarget_enc:
    n_fold: 15
    random_seed: 2023
    targetcol: ACTION
    columns: []

  random_catagory_encode:
    random_seed: 2023
    targetcol: ACTION
    random_cnt: 5
    columns:
    - RESOURCE
    - ROLE_ROLLUP_1
    - ROLE_ROLLUP_2
    - ROLE_DEPTNAME
    - ROLE_FAMILY_DESC
    - ROLE_FAMILY
    - ROLE_CODE
  fequency_encode:
    min_group_size: 2
    n_fold: 5
    random_seed: 2023
    targetcol: ACTION
    log_transform: true
    columns:
    - ROLE_DEPTNAME
    - ROLE_ROLLUP_1_ROLE_DEPTNAME
    - ROLE_ROLLUP_2_ROLE_DEPTNAME
    - ROLE_ROLLUP_2_ROLE_CODE
    - ROLE_DEPTNAME_ROLE_FAMILY_DESC
    - ROLE_DEPTNAME_ROLE_FAMILY
    - ROLE_DEPTNAME_ROLE_CODE
  tfidf:
    random_seed: 2023
    pair_columns:
    - RESOURCE
    permute_columns:
    - ROLE_ROLLUP_1
    - ROLE_ROLLUP_2
    - ROLE_FAMILY
    - ROLE_CODE
    - ROLE_ROLLUP_2_ROLE_CODE
    targetcol: ACTION
    combine_columns_required: false
    #dim_reduction: 1
    #var_explained: 0.2
    dim_reduction:
      ROLE_ROLLUP_1: 27
      ROLE_ROLLUP_2: 21
      #ROLE_DEPTNAME: 129
      #ROLE_FAMILY_DESC: 328
      ROLE_FAMILY: 15
      ROLE_CODE: 60
      #ROLE_ROLLUP_1_ROLE_DEPTNAME: 160
      #ROLE_ROLLUP_2_ROLE_DEPTNAME: 154
      ROLE_ROLLUP_2_ROLE_CODE: 90
      #ROLE_DEPTNAME_ROLE_FAMILY_DESC: 317
      #ROLE_DEPTNAME_ROLE_FAMILY: 130
      #ROLE_DEPTNAME_ROLE_CODE: 186

    #columns: [ 'ROLE_DEPTNAME', 'ROLE_FAMILY_DESC', 'ROLE_CODE', 'ROLE_ROLLUP_2', 'ROLE_ROLLUP_1', 'ROLE_FAMILY', 'RESOURCE', 'ROLE_ROLLUP_1_ROLE_ROLLUP_2','ROLE_FAMILY_ROLE_CODE', 'ROLE_ROLLUP_1_ROLE_FAMILY', 'ROLE_ROLLUP_2_ROLE_FAMILY', 'ROLE_ROLLUP_1_ROLE_DEPTNAME','ROLE_ROLLUP_2_ROLE_DEPTNAME','ROLE_ROLLUP_1_ROLE_CODE', 'ROLE_DEPTNAME_ROLE_FAMILY', 'ROLE_ROLLUP_2_ROLE_CODE']
    output:
      folder: feature\tfidf
      filename: tfidf.parquet

  count_vector:
    random_seed: 2023
    dim_reduction: 1
    var_explained: 0.9
    targetcol: ACTION
    combine_columns_required: false
    columns: []
    #columns: [ 'ROLE_DEPTNAME', 'ROLE_FAMILY_DESC', 'ROLE_CODE', 'ROLE_ROLLUP_2', 'ROLE_ROLLUP_1', 'ROLE_FAMILY', 'RESOURCE', 'ROLE_ROLLUP_1_ROLE_ROLLUP_2','ROLE_FAMILY_ROLE_CODE', 'ROLE_ROLLUP_1_ROLE_FAMILY', 'ROLE_ROLLUP_2_ROLE_FAMILY', 'ROLE_ROLLUP_1_ROLE_DEPTNAME','ROLE_ROLLUP_2_ROLE_DEPTNAME','ROLE_ROLLUP_1_ROLE_CODE', 'ROLE_DEPTNAME_ROLE_FAMILY', 'ROLE_ROLLUP_2_ROLE_CODE']
    output:
      folder: feature\cntvector
      filename: count_vectorizer.parquet

train_test_split:
  test_size: 0.01
  random_seed: 7899
  cv: 5
  train_data: feature\train_data.parquet

model:
  model_type: decision_tree

  logistic_reg:

    pipeline_type:
      KFoldTE: true
      frequency_encoding: false
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: false
      count_vectorizer_encoding: true
      random_catagory_encode: false
      resource_catagory_encode: false

    hyper_params:
      random_state: 2023
      max_iter: 40
      penalty: l2
      solver: liblinear
      C: 11
      #class_weight: balanced

    trained_model: model\logistic_reg\model.pkl
    eval_metrics: model\logistic_reg\metrics
    eval_plots: model\logistic_reg\plots

  decision_tree:

    pipeline_type:
      KFoldTE: false
      frequency_encoding: true
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: false
      count_vectorizer_encoding: false
      random_catagory_encode: false
      resource_catagory_encode: true

    hyper_params:
      random_state: 988
      max_depth: 40
      splitter: best
      min_samples_leaf: 0.001
      max_features: 0.8    #0.3
      #min_samples_split: 0.01
      #class_weight: balanced

    trained_model: model\decision_tree\model.pkl
    eval_metrics: model\decision_tree\metrics
    eval_plots: model\decision_tree\plots

  extra_decision_tree:

    pipeline_type:
      KFoldTE: true
      frequency_encoding: false
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: true
      count_vectorizer_encoding: false
      random_catagory_encode: false
      resource_catagory_encode: false

    hyper_params:
      random_state: 56
      n_estimators: 55
      max_depth: 4

      bootstrap: true
      max_samples: 0.75  #Max sample to consider for bootstrap
      max_features: 0.7
      min_samples_leaf: 0.5

      class_weight: balanced #balanced

    trained_model: model\extra_decision_tree\model.pkl
    eval_metrics: model\extra_decision_tree\metrics
    eval_plots: model\extra_decision_tree\plots

  random_forest:

    pipeline_type:
      KFoldTE: false
      frequency_encoding: true
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: true
      count_vectorizer_encoding: false
      random_catagory_encode: false
      resource_catagory_encode: false

    hyper_params:
      random_state: 42
      n_estimators: 220
      max_depth: 5

      bootstrap: true
      max_samples: 0.5  #Max sample to consider for bootstrap
      max_features: 0.5
      min_samples_leaf: 0.005

      class_weight: balanced           #balanced
    trained_model: model\random_forest\model.pkl
    eval_metrics: model\random_forest\metrics
    eval_plots: model\random_forest\plots

  xgboost:

    pipeline_type:
      KFoldTE: false
      frequency_encoding: true
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: true
      count_vectorizer_encoding: false
      random_catagory_encode: false
      resource_catagory_encode: false

    hyper_params:
      n_estimators: 300
      reg_lambda: 1.1800000000000002
      max_depth: 4
      learning_rate: 0.01
      random_state: 2045
      colsample_bytree: 0.685

    trained_model: model\xgboost\model.pkl
    eval_metrics: model\xgboost\metrics
    eval_plots: model\xgboost\plots

trained_model:
  model_path: model\model.pkl
  feature_eng: model\feature_engg_pipeline.json

  params:
    random_state: 988
    max_depth: 40
    splitter: best
    min_samples_leaf: 0.001
    max_features: 0.8

  pipeline_type:
    KFoldTE: false
    frequency_encoding: true
    KFold_frequency_encoding: false
    tfidf_vectorizer_encoding: false
    count_vectorizer_encoding: false
    random_catagory_encode: false
    resource_catagory_encode: true

