data_source:
  data_folders: data
  training_data_folder:
    folder: training
    train: train.csv
    test: test.csv
  prepared:
    folder: prepared
    clean_train: clean_train.csv

featurize:

  tfidf:
    random_seed: 2023
    dim_reduction: 1
    var_explained: 0.2
    output:
      folder: feature\tfidf
      filename: tfidf.parquet

  count_vector:
    random_seed: 2023
    dim_reduction: 1
    var_explained: 0.9
    output:
      folder: feature\cntvector
      filename: count_vectorizer.parquet

train_test_split:
  test_size: 0.01
  random_seed: 45
  cv: 5
  train_data: feature\train_data.parquet

model:
  model_type: extra_decision_tree

  logistic_reg:

    pipeline_type:
      KFoldTE: true
      frequency_encoding: false
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: true
      count_vectorizer_encoding: false

    hyper_params:
      max_iter: 1000
      penalty: l2
      C: 10000
      class_weight: balanced

    trained_model: model\logistic_reg\model.pkl
    eval_metrics: model\logistic_reg\metrics
    eval_plots: model\logistic_reg\plots

  decision_tree:

    pipeline_type:
      KFoldTE: false
      frequency_encoding: true
      KFold_frequency_encoding: true
      tfidf_vectorizer_encoding: false
      count_vectorizer_encoding: true

    hyper_params:
      max_depth: 14
      splitter: best
      min_samples_leaf: 0.001
      max_features: 0.3
      #min_samples_split: 0.01
      class_weight: balanced

    trained_model: model\decision_tree\model.pkl
    eval_metrics: model\decision_tree\metrics
    eval_plots: model\decision_tree\plots

  extra_decision_tree:

    pipeline_type:
      KFoldTE: true
      frequency_encoding: false
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: false
      count_vectorizer_encoding: false

    hyper_params:
      n_estimators: 55
      max_depth: 4

      bootstrap: true
      max_samples: 0.75  #Max sample to consider for bootstrap
      max_features: 0.7
      min_samples_leaf: 0.5

      class_weight: balanced           #balanced

    trained_model: model\extra_decision_tree\model.pkl
    eval_metrics: model\extra_decision_tree\metrics
    eval_plots: model\extra_decision_tree\plots

  random_forest:

    pipeline_type:
      KFoldTE: false
      frequency_encoding: true
      KFold_frequency_encoding: false
      tfidf_vectorizer_encoding: true
      count_vectorizer_encoding: false

    hyper_params:
      n_estimators: 220
      max_depth: 5

      bootstrap: true
      max_samples: 0.5  #Max sample to consider for bootstrap
      max_features: 0.5
      min_samples_leaf: 0.005

      class_weight: balanced           #balanced
    trained_model: model\random_forest\model.pkl
    eval_metrics: model\random_forest\metrics
    eval_plots: model\random_forest\plots


trained_model:
  model_path: model\model.pkl
  feature_eng: model\feature_engg_pipeline.json

  params:
    max_depth: 14
    splitter: best
    min_samples_leaf: 0.001
    max_features: 0.3
    #min_samples_split: 0.01
    class_weight: balanced

  pipeline_type:
    KFoldTE: true
    frequency_encoding: false
    KFold_frequency_encoding: false
    tfidf_vectorizer_encoding: false
    count_vectorizer_encoding: true


